#!/bin/sh

~/.config/script/autostart &

bspc monitor -d TERM WEB FILES TEL DOC MEDIA SETT GIT

bspc config border_width 1
bspc config window_gap 7
bspc config top_padding 25
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config focused_border_color        "#000000"
bspc config normal_border_color         "#000000"
bspc config active_border_color         "#000000"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle false

bspc config pointer_modifier mod1
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc rule -a kitty desktop='^1'
bspc rule -a Brave desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a feh state=floating rectangle=800x600
bspc rule -a Zathura desktop='^5' state=tiled follow=on
