#!/bin/bash
picom &
polybar mybar &
dunst &
sxhkd &
feh --bg-scale --randomize  ~/.config/pics/* &
#feh --bg-scale  ~/.config/pics/15.jpg &
xsetroot -cursor_name left_ptr &
$HOME/.config/script/launch.sh &
bsp-layout set tall &
udiskie -a  -n -t &


ln -sfn "$cwd"$HOME/.config/zsh/.zsh-plugins ~/.zsh-plugins
ln -sfn "$cwd"$HOME/.config/zsh/.zprofile ~/.zprofile
ln -sfn "$cwd"$HOME/.config/zsh/.zshenv ~/.zshenv
ln -sfn "$cwd"$HOME/.config/zsh/.zshrc ~/.zshrc
